version: "3"

dotenv: [".env.development.local"]

tasks:
  default:
    cmds:
      - task --list
    silent: true

  catalog-service-client:
    desc: Update Catalog Service client
    cmds:
      - npx openapi-typescript-codegen --input $REACT_APP_CATALOG_SERVICE_URL/openapi.json --output ./src/api/catalog-service-client --client fetch --name CatalogServiceClient

  scan-manager-client:
    desc: Update Scan Manager client
    cmds:
      - npx openapi-typescript-codegen --input $REACT_APP_SCAN_MANAGER_URL/openapi.json --output ./src/api/scan-manager-client --client fetch --name ScanManagerClient

  analytic-service-client:
    desc: Update Analytic Service client
    cmds:
      - npx openapi-typescript-codegen --input $REACT_APP_ANALYTIC_SERVICE_URL/openapi.json --output ./src/api/analytic-service-client --client fetch --name AnalyticServiceClient

  update-all:
    desc: Update all clients
    cmds:
      - task: catalog-service-client
      - task: scan-manager-client
      - task: analytic-service-client
