[tool.poetry]
name = "catalog-service"
version = "0.1.0"
description = ""
authors = ["Mikhail Stepanov <wakamail923@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = "^0.28.0"
loguru = "^0.7.2"
asyncpg = "^0.29.0"
yoyo-migrations = "^8.2.0"
psycopg2 = "^2.9.9"
pypika = "^0.48.9"
pydantic = "^2.6.4"
ruff = "^0.3.2"
black = "^24.2.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
