[tool.poetry]
name = "scan-manager"
version = "0.1.0"
description = ""
authors = ["Mikhail Stepanov <wakamail923@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.29.0"
loguru = "^0.7.2"
asyncpg = "^0.29.0"
yoyo-migrations = "^8.2.0"
psycopg2 = "^2.9.9"
pypika = "^0.48.9"
pydantic = "^2.6.4"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
fastapi = "^0.110.1"
docker = "^7.0.0"
aiohttp = "^3.9.3"
aio-pika = "^9.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
