[tool.poetry]
name = "analytic-service"
version = "0.1.0"
description = ""
authors = ["Mikhail Stepanov <wakamail923@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.1"
uvicorn = "^0.29.0"
loguru = "^0.7.2"
asyncpg = "^0.29.0"
pypika = "^0.48.9"
yoyo-migrations = "^8.2.0"
psycopg2 = "^2.9.9"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
aio-pika = "^9.4.1"
aiohttp = "^3.9.5"
aio-scrapy = "^2.1.0"
pydantic = "^2.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
